### ISSUE TITLE
Broken by recent changes at Currys

### ISSUE THREAD

**Issue by TNechleba** [Jovetic/GPUSearch#1]
Hi, 

Thanks for putting this together, it's very handy! 

This worked great up until this morning when Curry's introduced a session verification redirect. 

Adding a timeout lets the request get redirected the first time and subsequent checks then work fine.

`$cards = Invoke-RestMethod -Uri $Card -TimeoutSec 10`

Thanks,

Tom

**Comment by Jovetic** [comment]
Thanks.  I've updated. I had been trying to get the information via their API, to make it lighter on their servers, but I cant seem to find delivery information. Just that they would deliver.
